# Change baseurl before deploy
baseURL = "/"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar

languageCode = "pt-br"
title = "Blog - Mas que Democracia?!"

defaultContentLanguage = "pt"

theme = "bootstrap"

# Change it to your Disqus shortname before using
disqusShortname = "blog-quedemocracia"
